// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WDG.DataAccess.Concrete.EntityFramework;

namespace WDG.DataAccess.Migrations
{
    [DbContext(typeof(WDGContext))]
    partial class WDGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WDG.Entities.Concrete.kurData", b =>
                {
                    b.Property<int>("kurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DovizAlis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DovizCinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DovizKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DovizSatis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EfektifAlis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EfektifSatis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kurID");

                    b.ToTable("kurData");
                });
#pragma warning restore 612, 618
        }
    }
}
